import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import react,{useState,useEffect} from 'react'
import axios from 'axios'
import { signIn } from "next-auth/react";
import { useRouter } from 'next/router'

export default function Home() {
  const [account,setAccount] = useState('')
  const [password,setPassword] = useState('')
  const router = useRouter();
  const handleSubmit = async (e) => {
    e.preventDefault()
    const result = await signIn("credentials", {
      redirect: false,
      account,
      password,
    });

    if (result?.ok) {
      router.push("/products");
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

     <main>
       <form action="" onSubmit={handleSubmit}>
        <input type="text" onChange={e => setAccount(e.target.value)}/>
        <input type="text" onChange={e => setPassword(e.target.value)}/>
        <button>send</button>
       </form>
      
     </main>
    </div>
  )
}
